// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MyHalp.Editor.MyPreloader
{
    using UnityEngine.Audio;
    using System;
    using System.Collections;
    using System.Linq;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\MyHalp\MyHalp.Editor\Editor\MyPreloader\MyAssetsGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class MyAssetsGenerator : MyAssetsGeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n");
            this.Write("\r\nusing UnityEngine;\r\nusing UnityEngine.Audio;\r\nusing System;\r\nusing System.Colle" +
                    "ctions;\r\n\r\nnamespace MyHalp \r\n{\r\n\tpublic class MyAssets \r\n\t{\r\n");
            
            #line 19 "D:\MyHalp\MyHalp.Editor\Editor\MyPreloader\MyAssetsGenerator.tt"
 foreach(var asset in Assets) { 
            
            #line default
            #line hidden
            
            #line 20 "D:\MyHalp\MyHalp.Editor\Editor\MyPreloader\MyAssetsGenerator.tt"
 if(!string.IsNullOrEmpty(asset.Define)) { Write("#if " + asset.Define + "\n"); } 
            
            #line default
            #line hidden
            this.Write("\t\tpublic static ");
            
            #line 21 "D:\MyHalp\MyHalp.Editor\Editor\MyPreloader\MyAssetsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(asset.AssetType.ToString().Split('.').Last()));
            
            #line default
            #line hidden
            
            #line 21 "D:\MyHalp\MyHalp.Editor\Editor\MyPreloader\MyAssetsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(asset.IsArray ? "[]" : ""));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 21 "D:\MyHalp\MyHalp.Editor\Editor\MyPreloader\MyAssetsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(asset.FriendlyName));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 22 "D:\MyHalp\MyHalp.Editor\Editor\MyPreloader\MyAssetsGenerator.tt"
 if(!string.IsNullOrEmpty(asset.Define)) { Write("#endif\n"); } 
            
            #line default
            #line hidden
            
            #line 23 "D:\MyHalp\MyHalp.Editor\Editor\MyPreloader\MyAssetsGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"
		/// <summary>
		/// Preloads all assets, this should be called only once, unless you call Unload.
		/// </summary>
		public static void Init(Action onLoad = null, Action<string> onError = null) {
			IsLoaded = false;

			// run loader
			MyDispatcher.Handle.StartCoroutine(Loader(onLoad, onError));
		}

		// private
		private static IEnumerator Loader(Action onLoad, Action<string> onError) {
			ResourceRequest request;
			
			// fix when there is no any assets added
			yield return new WaitForEndOfFrame();

");
            
            #line 42 "D:\MyHalp\MyHalp.Editor\Editor\MyPreloader\MyAssetsGenerator.tt"
 foreach(var asset in Assets) { 
            
            #line default
            #line hidden
            
            #line 43 "D:\MyHalp\MyHalp.Editor\Editor\MyPreloader\MyAssetsGenerator.tt"
 if(!string.IsNullOrEmpty(asset.Define)) { Write("#if " + asset.Define + "\n"); } 
            
            #line default
            #line hidden
            
            #line 44 "D:\MyHalp\MyHalp.Editor\Editor\MyPreloader\MyAssetsGenerator.tt"
 if(asset.IsArray) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 45 "D:\MyHalp\MyHalp.Editor\Editor\MyPreloader\MyAssetsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(asset.FriendlyName));
            
            #line default
            #line hidden
            this.Write(" = new ");
            
            #line 45 "D:\MyHalp\MyHalp.Editor\Editor\MyPreloader\MyAssetsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(asset.AssetType.ToString().Split('.').Last()));
            
            #line default
            #line hidden
            this.Write("[");
            
            #line 45 "D:\MyHalp\MyHalp.Editor\Editor\MyPreloader\MyAssetsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(asset.ResourcePath.Length));
            
            #line default
            #line hidden
            this.Write("];\r\n\r\n");
            
            #line 47 "D:\MyHalp\MyHalp.Editor\Editor\MyPreloader\MyAssetsGenerator.tt"
 var i = 0; 
            
            #line default
            #line hidden
            
            #line 48 "D:\MyHalp\MyHalp.Editor\Editor\MyPreloader\MyAssetsGenerator.tt"
 foreach(var path in asset.ResourcePath) { 
            
            #line default
            #line hidden
            this.Write("\t\t\trequest = Resources.LoadAsync<");
            
            #line 49 "D:\MyHalp\MyHalp.Editor\Editor\MyPreloader\MyAssetsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(asset.AssetType.ToString().Split('.').Last()));
            
            #line default
            #line hidden
            this.Write(">(\"");
            
            #line 49 "D:\MyHalp\MyHalp.Editor\Editor\MyPreloader\MyAssetsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(path));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\tyield return request;\r\n\t\t\tif(request.asset == null) \r\n\t\t\t\tonError(\"Failed" +
                    " to load asset: ");
            
            #line 52 "D:\MyHalp\MyHalp.Editor\Editor\MyPreloader\MyAssetsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(asset.FriendlyName));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t");
            
            #line 53 "D:\MyHalp\MyHalp.Editor\Editor\MyPreloader\MyAssetsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(asset.FriendlyName));
            
            #line default
            #line hidden
            this.Write("[");
            
            #line 53 "D:\MyHalp\MyHalp.Editor\Editor\MyPreloader\MyAssetsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write("] = request.asset as ");
            
            #line 53 "D:\MyHalp\MyHalp.Editor\Editor\MyPreloader\MyAssetsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(asset.AssetType.ToString().Split('.').Last()));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 54 "D:\MyHalp\MyHalp.Editor\Editor\MyPreloader\MyAssetsGenerator.tt"
 i++; 
            
            #line default
            #line hidden
            
            #line 55 "D:\MyHalp\MyHalp.Editor\Editor\MyPreloader\MyAssetsGenerator.tt"
 } 
            
            #line default
            #line hidden
            
            #line 56 "D:\MyHalp\MyHalp.Editor\Editor\MyPreloader\MyAssetsGenerator.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\t\t\trequest = Resources.LoadAsync<");
            
            #line 57 "D:\MyHalp\MyHalp.Editor\Editor\MyPreloader\MyAssetsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(asset.AssetType.ToString().Split('.').Last()));
            
            #line default
            #line hidden
            this.Write(">(\"");
            
            #line 57 "D:\MyHalp\MyHalp.Editor\Editor\MyPreloader\MyAssetsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(asset.ResourcePath[0]));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\tyield return request;\r\n\t\t\tif(request.asset == null) \r\n\t\t\t\tonError(\"Failed" +
                    " to load asset: ");
            
            #line 60 "D:\MyHalp\MyHalp.Editor\Editor\MyPreloader\MyAssetsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(asset.FriendlyName));
            
            #line default
            #line hidden
            this.Write("\");\r\n\t\t\t");
            
            #line 61 "D:\MyHalp\MyHalp.Editor\Editor\MyPreloader\MyAssetsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(asset.FriendlyName));
            
            #line default
            #line hidden
            this.Write(" = request.asset as ");
            
            #line 61 "D:\MyHalp\MyHalp.Editor\Editor\MyPreloader\MyAssetsGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(asset.AssetType.ToString().Split('.').Last()));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 62 "D:\MyHalp\MyHalp.Editor\Editor\MyPreloader\MyAssetsGenerator.tt"
 } 
            
            #line default
            #line hidden
            
            #line 63 "D:\MyHalp\MyHalp.Editor\Editor\MyPreloader\MyAssetsGenerator.tt"
 if(!string.IsNullOrEmpty(asset.Define)) { Write("#endif\n"); } 
            
            #line default
            #line hidden
            
            #line 64 "D:\MyHalp\MyHalp.Editor\Editor\MyPreloader\MyAssetsGenerator.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\tif (onLoad != null)\r\n                onLoad();\r\n\t\t}\r\n\r\n\t\t/// <summary>\r\n\t\t/// " +
                    "Are the assets loaded?\r\n\t\t/// </summary>\r\n\t\tpublic static bool IsLoaded { get; p" +
                    "rivate set; }\r\n\t}\r\n}");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "D:\MyHalp\MyHalp.Editor\Editor\MyPreloader\MyAssetsGenerator.tt"

private MyHalp.Editor.MyPreloader.MyPreloaderSettings.Asset[] _AssetsField;

/// <summary>
/// Access the Assets parameter of the template.
/// </summary>
private global::MyHalp.Editor.MyPreloader.MyPreloaderSettings.Asset[] Assets
{
    get
    {
        return this._AssetsField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool AssetsValueAcquired = false;
if (this.Session.ContainsKey("Assets"))
{
    this._AssetsField = ((global::MyHalp.Editor.MyPreloader.MyPreloaderSettings.Asset[])(this.Session["Assets"]));
    AssetsValueAcquired = true;
}
if ((AssetsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Assets");
    if ((data != null))
    {
        this._AssetsField = ((global::MyHalp.Editor.MyPreloader.MyPreloaderSettings.Asset[])(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class MyAssetsGeneratorBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
